apiVersion: v1
kind: Pod
metadata:
  name: network-tools
spec:
  containers:
  - name: network-tools
    image: git.cryptic.systems/volker.raschek/network-tools:latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 250m
        memory: 250Mi
      requests:
        cpu: 100m
        memory: 125Mi
    securityContext:
      capabilities :
        add:
        - NET_ADMIN
        - SYS_TIME
      runAsUser: 1000
  restartPolicy: Always